/* SPDX-FileCopyrightText: 2014-present Kriasoft */
/* SPDX-License-Identifier: MIT */

import {
  AuthPlus,
  identitytoolkit,
  identitytoolkit_v3,
} from "@googleapis/identitytoolkit";

/**
 * Test user accounts generated by https://randomuser.me/.
 */
export const testUsers: identitytoolkit_v3.Schema$UserInfo[] = [
  {
    localId: "test-erika",
    screenName: "erika",
    email: "erika.pearson@example.com",
    emailVerified: true,
    phoneNumber: "+14788078434",
    displayName: "Erika Pearson",
    photoUrl: "https://randomuser.me/api/portraits/women/29.jpg",
    rawPassword: "paloma",
    createdAt: new Date("2024-01-01T12:00:00Z").getTime().toString(),
    lastLoginAt: new Date("2024-01-01T12:00:00Z").getTime().toString(),
  },
  {
    localId: "test-ryan",
    screenName: "ryan",
    email: "ryan.hunt@example.com",
    emailVerified: true,
    phoneNumber: "+16814758216",
    displayName: "Ryan Hunt",
    photoUrl: "https://randomuser.me/api/portraits/men/20.jpg",
    rawPassword: "baggins",
    createdAt: new Date("2024-01-02T12:00:00Z").getTime().toString(),
    lastLoginAt: new Date("2024-01-02T12:00:00Z").getTime().toString(),
  },
  {
    localId: "test-marian",
    screenName: "marian",
    email: "marian.stone@example.com",
    emailVerified: true,
    phoneNumber: "+19243007975",
    displayName: "Marian Stone",
    photoUrl: "https://randomuser.me/api/portraits/women/2.jpg",
    rawPassword: "winter1",
    createdAt: new Date("2024-01-03T12:00:00Z").getTime().toString(),
    lastLoginAt: new Date("2024-01-03T12:00:00Z").getTime().toString(),
  },
  {
    localId: "test-kurt",
    screenName: "kurt",
    email: "kurt.howward@example.com",
    emailVerified: true,
    phoneNumber: "+19243007975",
    displayName: "Kurt Howard",
    photoUrl: "https://randomuser.me/api/portraits/men/23.jpg",
    rawPassword: "mayday",
    createdAt: new Date("2024-01-04T12:00:00Z").getTime().toString(),
    lastLoginAt: new Date("2024-01-04T12:00:00Z").getTime().toString(),
  },
  {
    localId: "test-dan",
    screenName: "dan",
    email: "dan.day@example.com",
    emailVerified: true,
    phoneNumber: "+12046748092",
    displayName: "Dan Day",
    photoUrl: "https://randomuser.me/api/portraits/men/65.jpg",
    rawPassword: "teresa",
    createdAt: new Date("2024-01-05T12:00:00Z").getTime().toString(),
    lastLoginAt: new Date("2024-01-05T12:00:00Z").getTime().toString(),
    customAttributes: JSON.stringify({ admin: true }),
  },
];

/**
 * Seeds the Google Identity Platform (Firebase Auth) with test user accounts.
 *
 * @see https://randomuser.me/
 * @see https://cloud.google.com/identity-platform
 */
export async function seed() {
  const auth = new AuthPlus();
  const { relyingparty } = identitytoolkit({ version: "v3", auth });
  await relyingparty.uploadAccount({ requestBody: { users: testUsers } });
}
