enableGlobalCache: true

nodeLinker: pnp

packageExtensions:
  "@miniflare/r2@*":
    dependencies:
      "@miniflare/core": ^2.14.0
  "local-pkg@*":
    dependencies:
      "happy-dom": ^9.20.3

yarnPath: .yarn/releases/yarn-4.0.0-rc.45.cjs
