packageExtensions:
  babel-plugin-relay@*:
    dependencies:
      "@babel/runtime": ^7.14.0
  html-webpack-plugin@*:
    dependencies:
      loader-utils: ^2.0.0
  relay-compiler@*:
    dependencies:
      relay-compiler-language-typescript: ^14.0.0
      relay-config: ^11.0.2

yarnPath: .yarn/releases/yarn-4.0.0-rc.6.cjs
