/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule indexQuery.graphql
 * @generated SignedSource<<b12991e248c9d2bbfb663871f218eadc>>
 * @relayHash c7f2b038e43e16a9d3226c55b945fc95
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query indexQuery {
  news {
    ...Home_news
  }
}

fragment Home_news on NewsItem {
  title
  link
  author
  pubDate
  content
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "indexQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "NewsItem",
        "name": "news",
        "plural": true,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Home_news",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "indexQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "indexQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "NewsItem",
        "name": "news",
        "plural": true,
        "selections": [
          {
            "kind": "InlineFragment",
            "type": "NewsItem",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "title",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "link",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "author",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "pubDate",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "content",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query indexQuery {\n  news {\n    ...Home_news\n  }\n}\n\nfragment Home_news on NewsItem {\n  title\n  link\n  author\n  pubDate\n  content\n}\n"
};

module.exports = batch;
