/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule indexHomeQuery.graphql
 * @generated SignedSource<<805320f5778e5b16ea4968f8cb403d25>>
 * @relayHash f5535be2f7ad4c3ff31f1ebe70e29adc
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query indexHomeQuery {
  me {
    ...Layout_me
    id
  }
  news {
    ...Home_news
  }
}

fragment Layout_me on User {
  ...Header_me
}

fragment Home_news on NewsItem {
  title
  link
  author
  pubDate
  content
}

fragment Header_me on User {
  ...Navigation_me
}

fragment Navigation_me on User {
  email
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "indexHomeQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "me",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Layout_me",
            "args": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "NewsItem",
        "name": "news",
        "plural": true,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Home_news",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "indexHomeQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "indexHomeQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "me",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "email",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      },
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "NewsItem",
        "name": "news",
        "plural": true,
        "selections": [
          {
            "kind": "InlineFragment",
            "type": "NewsItem",
            "selections": [
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "title",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "link",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "author",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "pubDate",
                "storageKey": null
              },
              {
                "kind": "ScalarField",
                "alias": null,
                "args": null,
                "name": "content",
                "storageKey": null
              }
            ]
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query indexHomeQuery {\n  me {\n    ...Layout_me\n    id\n  }\n  news {\n    ...Home_news\n  }\n}\n\nfragment Layout_me on User {\n  ...Header_me\n}\n\nfragment Home_news on NewsItem {\n  title\n  link\n  author\n  pubDate\n  content\n}\n\nfragment Header_me on User {\n  ...Navigation_me\n}\n\nfragment Navigation_me on User {\n  email\n}\n"
};

module.exports = batch;
