// flow-typed signature: a8971ead399bafc880fd17c5eb3d898a
// flow-typed version: <<STUB>>/apollo-link-logger_v^1.2.3/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-logger'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-logger' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-logger/es/__tests__/formatMessage.test' {
  declare module.exports: any;
}

declare module 'apollo-link-logger/es/__tests__/logging.test' {
  declare module.exports: any;
}

declare module 'apollo-link-logger/es/formatMessage' {
  declare module.exports: any;
}

declare module 'apollo-link-logger/es/index' {
  declare module.exports: any;
}

declare module 'apollo-link-logger/es/logging' {
  declare module.exports: any;
}

declare module 'apollo-link-logger/lib/__tests__/formatMessage.test' {
  declare module.exports: any;
}

declare module 'apollo-link-logger/lib/__tests__/logging.test' {
  declare module.exports: any;
}

declare module 'apollo-link-logger/lib/formatMessage' {
  declare module.exports: any;
}

declare module 'apollo-link-logger/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-logger/lib/logging' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-logger/es/__tests__/formatMessage.test.js' {
  declare module.exports: $Exports<
    'apollo-link-logger/es/__tests__/formatMessage.test',
  >;
}
declare module 'apollo-link-logger/es/__tests__/logging.test.js' {
  declare module.exports: $Exports<
    'apollo-link-logger/es/__tests__/logging.test',
  >;
}
declare module 'apollo-link-logger/es/formatMessage.js' {
  declare module.exports: $Exports<'apollo-link-logger/es/formatMessage'>;
}
declare module 'apollo-link-logger/es/index.js' {
  declare module.exports: $Exports<'apollo-link-logger/es/index'>;
}
declare module 'apollo-link-logger/es/logging.js' {
  declare module.exports: $Exports<'apollo-link-logger/es/logging'>;
}
declare module 'apollo-link-logger/lib/__tests__/formatMessage.test.js' {
  declare module.exports: $Exports<
    'apollo-link-logger/lib/__tests__/formatMessage.test',
  >;
}
declare module 'apollo-link-logger/lib/__tests__/logging.test.js' {
  declare module.exports: $Exports<
    'apollo-link-logger/lib/__tests__/logging.test',
  >;
}
declare module 'apollo-link-logger/lib/formatMessage.js' {
  declare module.exports: $Exports<'apollo-link-logger/lib/formatMessage'>;
}
declare module 'apollo-link-logger/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-logger/lib/index'>;
}
declare module 'apollo-link-logger/lib/logging.js' {
  declare module.exports: $Exports<'apollo-link-logger/lib/logging'>;
}
