// flow-typed signature: 9d79a09d6fe1d51aff442a1299326289
// flow-typed version: <<STUB>>/apollo-link_v^1.2.3/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link/lib/link' {
  declare module.exports: any;
}

declare module 'apollo-link/lib/linkUtils' {
  declare module.exports: any;
}

declare module 'apollo-link/lib/test-utils' {
  declare module.exports: any;
}

declare module 'apollo-link/lib/test-utils/mockLink' {
  declare module.exports: any;
}

declare module 'apollo-link/lib/test-utils/setContext' {
  declare module.exports: any;
}

declare module 'apollo-link/lib/test-utils/testingUtils' {
  declare module.exports: any;
}

declare module 'apollo-link/lib/types' {
  declare module.exports: any;
}

declare module 'apollo-link/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link/lib/bundle.umd'>;
}
declare module 'apollo-link/lib/index.js' {
  declare module.exports: $Exports<'apollo-link/lib/index'>;
}
declare module 'apollo-link/lib/link.js' {
  declare module.exports: $Exports<'apollo-link/lib/link'>;
}
declare module 'apollo-link/lib/linkUtils.js' {
  declare module.exports: $Exports<'apollo-link/lib/linkUtils'>;
}
declare module 'apollo-link/lib/test-utils.js' {
  declare module.exports: $Exports<'apollo-link/lib/test-utils'>;
}
declare module 'apollo-link/lib/test-utils/mockLink.js' {
  declare module.exports: $Exports<'apollo-link/lib/test-utils/mockLink'>;
}
declare module 'apollo-link/lib/test-utils/setContext.js' {
  declare module.exports: $Exports<'apollo-link/lib/test-utils/setContext'>;
}
declare module 'apollo-link/lib/test-utils/testingUtils.js' {
  declare module.exports: $Exports<'apollo-link/lib/test-utils/testingUtils'>;
}
declare module 'apollo-link/lib/types.js' {
  declare module.exports: $Exports<'apollo-link/lib/types'>;
}
declare module 'apollo-link/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link/rollup.config'>;
}
