// flow-typed signature: 960df8061fbaa416ba8c4d96cd04890f
// flow-typed version: <<STUB>>/apollo-server_v^2.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-server'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-server' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-server/dist/exports' {
  declare module.exports: any;
}

declare module 'apollo-server/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-server/dist/exports.js' {
  declare module.exports: $Exports<'apollo-server/dist/exports'>;
}
declare module 'apollo-server/dist/index.js' {
  declare module.exports: $Exports<'apollo-server/dist/index'>;
}
