// flow-typed signature: 1a0e89419edad1d0679059c0d72e40a1
// flow-typed version: <<STUB>>/autoprefixer_v^9.1.5/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'autoprefixer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'autoprefixer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'autoprefixer/data/prefixes' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/at-rule' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/autoprefixer' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/brackets' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/browsers' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/declaration' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/align-content' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/align-items' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/align-self' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/animation' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/appearance' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/background-clip' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/background-size' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/block-logical' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/border-image' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/border-radius' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/break-props' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/color-adjust' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/cross-fade' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/display-flex' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/display-grid' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/filter-value' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/filter' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/flex-basis' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/flex-direction' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/flex-flow' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/flex-grow' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/flex-shrink' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/flex-spec' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/flex-wrap' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/flex' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/fullscreen' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/gradient' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-area' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-column-align' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-end' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-row-align' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-row-column' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-rows-columns' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-start' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-template-areas' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-template' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/grid-utils' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/image-rendering' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/image-set' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/inline-logical' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/intrinsic' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/justify-content' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/mask-border' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/order' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/overscroll-behavior' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/pixelated' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/placeholder' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/text-decoration' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/text-emphasis-position' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/transform-decl' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/hacks/writing-mode' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/info' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/old-selector' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/old-value' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/prefixer' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/prefixes' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/processor' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/resolution' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/selector' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/supports' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/transition' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/utils' {
  declare module.exports: any;
}

declare module 'autoprefixer/lib/value' {
  declare module.exports: any;
}

// Filename aliases
declare module 'autoprefixer/data/prefixes.js' {
  declare module.exports: $Exports<'autoprefixer/data/prefixes'>;
}
declare module 'autoprefixer/lib/at-rule.js' {
  declare module.exports: $Exports<'autoprefixer/lib/at-rule'>;
}
declare module 'autoprefixer/lib/autoprefixer.js' {
  declare module.exports: $Exports<'autoprefixer/lib/autoprefixer'>;
}
declare module 'autoprefixer/lib/brackets.js' {
  declare module.exports: $Exports<'autoprefixer/lib/brackets'>;
}
declare module 'autoprefixer/lib/browsers.js' {
  declare module.exports: $Exports<'autoprefixer/lib/browsers'>;
}
declare module 'autoprefixer/lib/declaration.js' {
  declare module.exports: $Exports<'autoprefixer/lib/declaration'>;
}
declare module 'autoprefixer/lib/hacks/align-content.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/align-content'>;
}
declare module 'autoprefixer/lib/hacks/align-items.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/align-items'>;
}
declare module 'autoprefixer/lib/hacks/align-self.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/align-self'>;
}
declare module 'autoprefixer/lib/hacks/animation.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/animation'>;
}
declare module 'autoprefixer/lib/hacks/appearance.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/appearance'>;
}
declare module 'autoprefixer/lib/hacks/background-clip.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/background-clip'>;
}
declare module 'autoprefixer/lib/hacks/background-size.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/background-size'>;
}
declare module 'autoprefixer/lib/hacks/block-logical.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/block-logical'>;
}
declare module 'autoprefixer/lib/hacks/border-image.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/border-image'>;
}
declare module 'autoprefixer/lib/hacks/border-radius.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/border-radius'>;
}
declare module 'autoprefixer/lib/hacks/break-props.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/break-props'>;
}
declare module 'autoprefixer/lib/hacks/color-adjust.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/color-adjust'>;
}
declare module 'autoprefixer/lib/hacks/cross-fade.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/cross-fade'>;
}
declare module 'autoprefixer/lib/hacks/display-flex.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/display-flex'>;
}
declare module 'autoprefixer/lib/hacks/display-grid.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/display-grid'>;
}
declare module 'autoprefixer/lib/hacks/filter-value.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/filter-value'>;
}
declare module 'autoprefixer/lib/hacks/filter.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/filter'>;
}
declare module 'autoprefixer/lib/hacks/flex-basis.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/flex-basis'>;
}
declare module 'autoprefixer/lib/hacks/flex-direction.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/flex-direction'>;
}
declare module 'autoprefixer/lib/hacks/flex-flow.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/flex-flow'>;
}
declare module 'autoprefixer/lib/hacks/flex-grow.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/flex-grow'>;
}
declare module 'autoprefixer/lib/hacks/flex-shrink.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/flex-shrink'>;
}
declare module 'autoprefixer/lib/hacks/flex-spec.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/flex-spec'>;
}
declare module 'autoprefixer/lib/hacks/flex-wrap.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/flex-wrap'>;
}
declare module 'autoprefixer/lib/hacks/flex.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/flex'>;
}
declare module 'autoprefixer/lib/hacks/fullscreen.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/fullscreen'>;
}
declare module 'autoprefixer/lib/hacks/gradient.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/gradient'>;
}
declare module 'autoprefixer/lib/hacks/grid-area.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/grid-area'>;
}
declare module 'autoprefixer/lib/hacks/grid-column-align.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/grid-column-align'>;
}
declare module 'autoprefixer/lib/hacks/grid-end.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/grid-end'>;
}
declare module 'autoprefixer/lib/hacks/grid-row-align.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/grid-row-align'>;
}
declare module 'autoprefixer/lib/hacks/grid-row-column.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/grid-row-column'>;
}
declare module 'autoprefixer/lib/hacks/grid-rows-columns.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/grid-rows-columns'>;
}
declare module 'autoprefixer/lib/hacks/grid-start.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/grid-start'>;
}
declare module 'autoprefixer/lib/hacks/grid-template-areas.js' {
  declare module.exports: $Exports<
    'autoprefixer/lib/hacks/grid-template-areas',
  >;
}
declare module 'autoprefixer/lib/hacks/grid-template.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/grid-template'>;
}
declare module 'autoprefixer/lib/hacks/grid-utils.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/grid-utils'>;
}
declare module 'autoprefixer/lib/hacks/image-rendering.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/image-rendering'>;
}
declare module 'autoprefixer/lib/hacks/image-set.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/image-set'>;
}
declare module 'autoprefixer/lib/hacks/inline-logical.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/inline-logical'>;
}
declare module 'autoprefixer/lib/hacks/intrinsic.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/intrinsic'>;
}
declare module 'autoprefixer/lib/hacks/justify-content.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/justify-content'>;
}
declare module 'autoprefixer/lib/hacks/mask-border.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/mask-border'>;
}
declare module 'autoprefixer/lib/hacks/order.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/order'>;
}
declare module 'autoprefixer/lib/hacks/overscroll-behavior.js' {
  declare module.exports: $Exports<
    'autoprefixer/lib/hacks/overscroll-behavior',
  >;
}
declare module 'autoprefixer/lib/hacks/pixelated.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/pixelated'>;
}
declare module 'autoprefixer/lib/hacks/placeholder.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/placeholder'>;
}
declare module 'autoprefixer/lib/hacks/text-decoration.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/text-decoration'>;
}
declare module 'autoprefixer/lib/hacks/text-emphasis-position.js' {
  declare module.exports: $Exports<
    'autoprefixer/lib/hacks/text-emphasis-position',
  >;
}
declare module 'autoprefixer/lib/hacks/transform-decl.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/transform-decl'>;
}
declare module 'autoprefixer/lib/hacks/writing-mode.js' {
  declare module.exports: $Exports<'autoprefixer/lib/hacks/writing-mode'>;
}
declare module 'autoprefixer/lib/info.js' {
  declare module.exports: $Exports<'autoprefixer/lib/info'>;
}
declare module 'autoprefixer/lib/old-selector.js' {
  declare module.exports: $Exports<'autoprefixer/lib/old-selector'>;
}
declare module 'autoprefixer/lib/old-value.js' {
  declare module.exports: $Exports<'autoprefixer/lib/old-value'>;
}
declare module 'autoprefixer/lib/prefixer.js' {
  declare module.exports: $Exports<'autoprefixer/lib/prefixer'>;
}
declare module 'autoprefixer/lib/prefixes.js' {
  declare module.exports: $Exports<'autoprefixer/lib/prefixes'>;
}
declare module 'autoprefixer/lib/processor.js' {
  declare module.exports: $Exports<'autoprefixer/lib/processor'>;
}
declare module 'autoprefixer/lib/resolution.js' {
  declare module.exports: $Exports<'autoprefixer/lib/resolution'>;
}
declare module 'autoprefixer/lib/selector.js' {
  declare module.exports: $Exports<'autoprefixer/lib/selector'>;
}
declare module 'autoprefixer/lib/supports.js' {
  declare module.exports: $Exports<'autoprefixer/lib/supports'>;
}
declare module 'autoprefixer/lib/transition.js' {
  declare module.exports: $Exports<'autoprefixer/lib/transition'>;
}
declare module 'autoprefixer/lib/utils.js' {
  declare module.exports: $Exports<'autoprefixer/lib/utils'>;
}
declare module 'autoprefixer/lib/value.js' {
  declare module.exports: $Exports<'autoprefixer/lib/value'>;
}
