// flow-typed signature: 50f9ccac954a4b47a5dbfd86d901d925
// flow-typed version: <<STUB>>/browser-sync_v^2.24.7/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-sync'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-sync' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-sync/changelog' {
  declare module.exports: any;
}

declare module 'browser-sync/client/dist/index' {
  declare module.exports: any;
}

declare module 'browser-sync/client/dist/index.min' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/args' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/async-tasks' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/async' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/bin' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/browser-sync' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/cli-info' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/cli-options' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/command.init' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/command.recipe' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/command.reload' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/command.start' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/addCwdToWatchOptions' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/addDefaultIgnorePatterns' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/addToFilesOption' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/appendServerDirectoryOption' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/appendServerIndexOption' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/copyCLIIgnoreToWatchOptions' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/handleExtensionsOption' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/handleFilesOption' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/handleGhostModeOption' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/handlePortsOption' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/handleProxyOption' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/cli/transforms/handleServerOption' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/client' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/config' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/connect-utils' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/default-config' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/file-event-handler' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/file-utils' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/file-watcher' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/hooks' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/http-protocol' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/index' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/internal-events' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/lodash.custom' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/logger' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/options' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/plugins' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/public/exit' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/public/init' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/public/notify' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/public/pause' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/public/public-utils' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/public/reload' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/public/resume' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/public/stream' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/server/index' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/server/proxy-server' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/server/proxy-utils' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/server/snippet-server' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/server/static-server' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/server/utils' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/snippet' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/sockets' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/tunnel' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/types' {
  declare module.exports: any;
}

declare module 'browser-sync/dist/utils' {
  declare module.exports: any;
}

declare module 'browser-sync/templates/cli-template' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-sync/changelog.js' {
  declare module.exports: $Exports<'browser-sync/changelog'>;
}
declare module 'browser-sync/client/dist/index.js' {
  declare module.exports: $Exports<'browser-sync/client/dist/index'>;
}
declare module 'browser-sync/client/dist/index.min.js' {
  declare module.exports: $Exports<'browser-sync/client/dist/index.min'>;
}
declare module 'browser-sync/dist/args.js' {
  declare module.exports: $Exports<'browser-sync/dist/args'>;
}
declare module 'browser-sync/dist/async-tasks.js' {
  declare module.exports: $Exports<'browser-sync/dist/async-tasks'>;
}
declare module 'browser-sync/dist/async.js' {
  declare module.exports: $Exports<'browser-sync/dist/async'>;
}
declare module 'browser-sync/dist/bin.js' {
  declare module.exports: $Exports<'browser-sync/dist/bin'>;
}
declare module 'browser-sync/dist/browser-sync.js' {
  declare module.exports: $Exports<'browser-sync/dist/browser-sync'>;
}
declare module 'browser-sync/dist/cli/cli-info.js' {
  declare module.exports: $Exports<'browser-sync/dist/cli/cli-info'>;
}
declare module 'browser-sync/dist/cli/cli-options.js' {
  declare module.exports: $Exports<'browser-sync/dist/cli/cli-options'>;
}
declare module 'browser-sync/dist/cli/command.init.js' {
  declare module.exports: $Exports<'browser-sync/dist/cli/command.init'>;
}
declare module 'browser-sync/dist/cli/command.recipe.js' {
  declare module.exports: $Exports<'browser-sync/dist/cli/command.recipe'>;
}
declare module 'browser-sync/dist/cli/command.reload.js' {
  declare module.exports: $Exports<'browser-sync/dist/cli/command.reload'>;
}
declare module 'browser-sync/dist/cli/command.start.js' {
  declare module.exports: $Exports<'browser-sync/dist/cli/command.start'>;
}
declare module 'browser-sync/dist/cli/transforms/addCwdToWatchOptions.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/addCwdToWatchOptions',
  >;
}
declare module 'browser-sync/dist/cli/transforms/addDefaultIgnorePatterns.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/addDefaultIgnorePatterns',
  >;
}
declare module 'browser-sync/dist/cli/transforms/addToFilesOption.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/addToFilesOption',
  >;
}
declare module 'browser-sync/dist/cli/transforms/appendServerDirectoryOption.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/appendServerDirectoryOption',
  >;
}
declare module 'browser-sync/dist/cli/transforms/appendServerIndexOption.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/appendServerIndexOption',
  >;
}
declare module 'browser-sync/dist/cli/transforms/copyCLIIgnoreToWatchOptions.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/copyCLIIgnoreToWatchOptions',
  >;
}
declare module 'browser-sync/dist/cli/transforms/handleExtensionsOption.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/handleExtensionsOption',
  >;
}
declare module 'browser-sync/dist/cli/transforms/handleFilesOption.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/handleFilesOption',
  >;
}
declare module 'browser-sync/dist/cli/transforms/handleGhostModeOption.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/handleGhostModeOption',
  >;
}
declare module 'browser-sync/dist/cli/transforms/handlePortsOption.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/handlePortsOption',
  >;
}
declare module 'browser-sync/dist/cli/transforms/handleProxyOption.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/handleProxyOption',
  >;
}
declare module 'browser-sync/dist/cli/transforms/handleServerOption.js' {
  declare module.exports: $Exports<
    'browser-sync/dist/cli/transforms/handleServerOption',
  >;
}
declare module 'browser-sync/dist/client.js' {
  declare module.exports: $Exports<'browser-sync/dist/client'>;
}
declare module 'browser-sync/dist/config.js' {
  declare module.exports: $Exports<'browser-sync/dist/config'>;
}
declare module 'browser-sync/dist/connect-utils.js' {
  declare module.exports: $Exports<'browser-sync/dist/connect-utils'>;
}
declare module 'browser-sync/dist/default-config.js' {
  declare module.exports: $Exports<'browser-sync/dist/default-config'>;
}
declare module 'browser-sync/dist/file-event-handler.js' {
  declare module.exports: $Exports<'browser-sync/dist/file-event-handler'>;
}
declare module 'browser-sync/dist/file-utils.js' {
  declare module.exports: $Exports<'browser-sync/dist/file-utils'>;
}
declare module 'browser-sync/dist/file-watcher.js' {
  declare module.exports: $Exports<'browser-sync/dist/file-watcher'>;
}
declare module 'browser-sync/dist/hooks.js' {
  declare module.exports: $Exports<'browser-sync/dist/hooks'>;
}
declare module 'browser-sync/dist/http-protocol.js' {
  declare module.exports: $Exports<'browser-sync/dist/http-protocol'>;
}
declare module 'browser-sync/dist/index.js' {
  declare module.exports: $Exports<'browser-sync/dist/index'>;
}
declare module 'browser-sync/dist/internal-events.js' {
  declare module.exports: $Exports<'browser-sync/dist/internal-events'>;
}
declare module 'browser-sync/dist/lodash.custom.js' {
  declare module.exports: $Exports<'browser-sync/dist/lodash.custom'>;
}
declare module 'browser-sync/dist/logger.js' {
  declare module.exports: $Exports<'browser-sync/dist/logger'>;
}
declare module 'browser-sync/dist/options.js' {
  declare module.exports: $Exports<'browser-sync/dist/options'>;
}
declare module 'browser-sync/dist/plugins.js' {
  declare module.exports: $Exports<'browser-sync/dist/plugins'>;
}
declare module 'browser-sync/dist/public/exit.js' {
  declare module.exports: $Exports<'browser-sync/dist/public/exit'>;
}
declare module 'browser-sync/dist/public/init.js' {
  declare module.exports: $Exports<'browser-sync/dist/public/init'>;
}
declare module 'browser-sync/dist/public/notify.js' {
  declare module.exports: $Exports<'browser-sync/dist/public/notify'>;
}
declare module 'browser-sync/dist/public/pause.js' {
  declare module.exports: $Exports<'browser-sync/dist/public/pause'>;
}
declare module 'browser-sync/dist/public/public-utils.js' {
  declare module.exports: $Exports<'browser-sync/dist/public/public-utils'>;
}
declare module 'browser-sync/dist/public/reload.js' {
  declare module.exports: $Exports<'browser-sync/dist/public/reload'>;
}
declare module 'browser-sync/dist/public/resume.js' {
  declare module.exports: $Exports<'browser-sync/dist/public/resume'>;
}
declare module 'browser-sync/dist/public/stream.js' {
  declare module.exports: $Exports<'browser-sync/dist/public/stream'>;
}
declare module 'browser-sync/dist/server/index.js' {
  declare module.exports: $Exports<'browser-sync/dist/server/index'>;
}
declare module 'browser-sync/dist/server/proxy-server.js' {
  declare module.exports: $Exports<'browser-sync/dist/server/proxy-server'>;
}
declare module 'browser-sync/dist/server/proxy-utils.js' {
  declare module.exports: $Exports<'browser-sync/dist/server/proxy-utils'>;
}
declare module 'browser-sync/dist/server/snippet-server.js' {
  declare module.exports: $Exports<'browser-sync/dist/server/snippet-server'>;
}
declare module 'browser-sync/dist/server/static-server.js' {
  declare module.exports: $Exports<'browser-sync/dist/server/static-server'>;
}
declare module 'browser-sync/dist/server/utils.js' {
  declare module.exports: $Exports<'browser-sync/dist/server/utils'>;
}
declare module 'browser-sync/dist/snippet.js' {
  declare module.exports: $Exports<'browser-sync/dist/snippet'>;
}
declare module 'browser-sync/dist/sockets.js' {
  declare module.exports: $Exports<'browser-sync/dist/sockets'>;
}
declare module 'browser-sync/dist/tunnel.js' {
  declare module.exports: $Exports<'browser-sync/dist/tunnel'>;
}
declare module 'browser-sync/dist/types.js' {
  declare module.exports: $Exports<'browser-sync/dist/types'>;
}
declare module 'browser-sync/dist/utils.js' {
  declare module.exports: $Exports<'browser-sync/dist/utils'>;
}
declare module 'browser-sync/templates/cli-template.js' {
  declare module.exports: $Exports<'browser-sync/templates/cli-template'>;
}
