// flow-typed signature: 98251dac906508cb2cc92396d3902842
// flow-typed version: <<STUB>>/front-matter_v^2.3.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'front-matter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'front-matter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'front-matter/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'front-matter/index' {
  declare module.exports: $Exports<'front-matter'>;
}
declare module 'front-matter/index.js' {
  declare module.exports: $Exports<'front-matter'>;
}
declare module 'front-matter/test/index.js' {
  declare module.exports: $Exports<'front-matter/test/index'>;
}
