// flow-typed signature: cf35d4b22220555244d9320cad1f8f11
// flow-typed version: <<STUB>>/isomorphic-style-loader_v^4.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'isomorphic-style-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'isomorphic-style-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'isomorphic-style-loader/lib/index' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/lib/insertCss' {
  declare module.exports: any;
}

declare module 'isomorphic-style-loader/lib/withStyles' {
  // TODO: Using ComponentType<T> does not work so simply return T.
  // import type {ComponentType} from 'react';
  declare module.exports: (
    s1: string,
    s2?: string,
    s3?: string,
    s4?: string,
    s5?: string,
    ) => (<T>(component: T) => T);
}

// Filename aliases
declare module 'isomorphic-style-loader/lib/index.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/lib/index'>;
}
declare module 'isomorphic-style-loader/lib/insertCss.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/lib/insertCss'>;
}
declare module 'isomorphic-style-loader/lib/withStyles.js' {
  declare module.exports: $Exports<'isomorphic-style-loader/lib/withStyles'>;
}
