// flow-typed signature: caa775cb81e845b2b429d8a6ad219afb
// flow-typed version: <<STUB>>/jest-codemods_v^0.16.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jest-codemods'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jest-codemods' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jest-codemods/bin/jest-codemods' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/cli/git-status' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/cli/index' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/cli/transformers' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/ava' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/chai-assert' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/chai-should' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/expect-js' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/expect' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/jasmine-globals' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/jasmine-this' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/mocha' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/should' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/transformers/tape' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/chai-chain-utils' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/consts' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/finale' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/imports' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/line-terminator' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/logger' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/proxyquire' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/quote-style' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/recast-helpers' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/tape-ava-helpers' {
  declare module.exports: any;
}

declare module 'jest-codemods/dist/utils/test-helpers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jest-codemods/bin/jest-codemods.js' {
  declare module.exports: $Exports<'jest-codemods/bin/jest-codemods'>;
}
declare module 'jest-codemods/dist/cli/git-status.js' {
  declare module.exports: $Exports<'jest-codemods/dist/cli/git-status'>;
}
declare module 'jest-codemods/dist/cli/index.js' {
  declare module.exports: $Exports<'jest-codemods/dist/cli/index'>;
}
declare module 'jest-codemods/dist/cli/transformers.js' {
  declare module.exports: $Exports<'jest-codemods/dist/cli/transformers'>;
}
declare module 'jest-codemods/dist/transformers/ava.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/ava'>;
}
declare module 'jest-codemods/dist/transformers/chai-assert.js' {
  declare module.exports: $Exports<
    'jest-codemods/dist/transformers/chai-assert',
  >;
}
declare module 'jest-codemods/dist/transformers/chai-should.js' {
  declare module.exports: $Exports<
    'jest-codemods/dist/transformers/chai-should',
  >;
}
declare module 'jest-codemods/dist/transformers/expect-js.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/expect-js'>;
}
declare module 'jest-codemods/dist/transformers/expect.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/expect'>;
}
declare module 'jest-codemods/dist/transformers/jasmine-globals.js' {
  declare module.exports: $Exports<
    'jest-codemods/dist/transformers/jasmine-globals',
  >;
}
declare module 'jest-codemods/dist/transformers/jasmine-this.js' {
  declare module.exports: $Exports<
    'jest-codemods/dist/transformers/jasmine-this',
  >;
}
declare module 'jest-codemods/dist/transformers/mocha.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/mocha'>;
}
declare module 'jest-codemods/dist/transformers/should.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/should'>;
}
declare module 'jest-codemods/dist/transformers/tape.js' {
  declare module.exports: $Exports<'jest-codemods/dist/transformers/tape'>;
}
declare module 'jest-codemods/dist/utils/chai-chain-utils.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/chai-chain-utils'>;
}
declare module 'jest-codemods/dist/utils/consts.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/consts'>;
}
declare module 'jest-codemods/dist/utils/finale.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/finale'>;
}
declare module 'jest-codemods/dist/utils/imports.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/imports'>;
}
declare module 'jest-codemods/dist/utils/line-terminator.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/line-terminator'>;
}
declare module 'jest-codemods/dist/utils/logger.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/logger'>;
}
declare module 'jest-codemods/dist/utils/proxyquire.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/proxyquire'>;
}
declare module 'jest-codemods/dist/utils/quote-style.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/quote-style'>;
}
declare module 'jest-codemods/dist/utils/recast-helpers.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/recast-helpers'>;
}
declare module 'jest-codemods/dist/utils/tape-ava-helpers.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/tape-ava-helpers'>;
}
declare module 'jest-codemods/dist/utils/test-helpers.js' {
  declare module.exports: $Exports<'jest-codemods/dist/utils/test-helpers'>;
}
