// flow-typed signature: 4618c58dd366c44955488c590405500c
// flow-typed version: <<STUB>>/lodash.merge_v^4.6.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.merge'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.merge' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'lodash.merge/index' {
  declare module.exports: $Exports<'lodash.merge'>;
}
declare module 'lodash.merge/index.js' {
  declare module.exports: $Exports<'lodash.merge'>;
}
