// flow-typed signature: c1dc27bd05e1a741621391185eb866ad
// flow-typed version: <<STUB>>/passport-facebook_v^2.1.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'passport-facebook'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'passport-facebook' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'passport-facebook/lib/errors/facebookauthorizationerror' {
  declare module.exports: any;
}

declare module 'passport-facebook/lib/errors/facebookgraphapierror' {
  declare module.exports: any;
}

declare module 'passport-facebook/lib/errors/facebooktokenerror' {
  declare module.exports: any;
}

declare module 'passport-facebook/lib/index' {
  declare module.exports: any;
}

declare module 'passport-facebook/lib/profile' {
  declare module.exports: any;
}

declare module 'passport-facebook/lib/strategy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'passport-facebook/lib/errors/facebookauthorizationerror.js' {
  declare module.exports: $Exports<
    'passport-facebook/lib/errors/facebookauthorizationerror',
  >;
}
declare module 'passport-facebook/lib/errors/facebookgraphapierror.js' {
  declare module.exports: $Exports<
    'passport-facebook/lib/errors/facebookgraphapierror',
  >;
}
declare module 'passport-facebook/lib/errors/facebooktokenerror.js' {
  declare module.exports: $Exports<
    'passport-facebook/lib/errors/facebooktokenerror',
  >;
}
declare module 'passport-facebook/lib/index.js' {
  declare module.exports: $Exports<'passport-facebook/lib/index'>;
}
declare module 'passport-facebook/lib/profile.js' {
  declare module.exports: $Exports<'passport-facebook/lib/profile'>;
}
declare module 'passport-facebook/lib/strategy.js' {
  declare module.exports: $Exports<'passport-facebook/lib/strategy'>;
}
