// flow-typed signature: 82b948a2219e3ca6fad8b9b7e79a50db
// flow-typed version: <<STUB>>/pleeease-filters_v^4.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pleeease-filters'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pleeease-filters' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'pleeease-filters/index' {
  declare module.exports: $Exports<'pleeease-filters'>;
}
declare module 'pleeease-filters/index.js' {
  declare module.exports: $Exports<'pleeease-filters'>;
}
