// flow-typed signature: d081c271abdcafb4c8e1b6af999e250a
// flow-typed version: <<STUB>>/postcss-pseudoelements_v^5.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-pseudoelements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-pseudoelements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-pseudoelements/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-pseudoelements/index' {
  declare module.exports: $Exports<'postcss-pseudoelements'>;
}
declare module 'postcss-pseudoelements/index.js' {
  declare module.exports: $Exports<'postcss-pseudoelements'>;
}
declare module 'postcss-pseudoelements/test/test.js' {
  declare module.exports: $Exports<'postcss-pseudoelements/test/test'>;
}
