// flow-typed signature: 2eb5025dce16e669ede01374ec97339f
// flow-typed version: <<STUB>>/postcss-color-function_v^4.0.1/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-color-function'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-color-function' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'postcss-color-function/index' {
  declare module.exports: $Exports<'postcss-color-function'>;
}
declare module 'postcss-color-function/index.js' {
  declare module.exports: $Exports<'postcss-color-function'>;
}
