// flow-typed signature: 7383ae0f74f737a3372787f35ba02600
// flow-typed version: <<STUB>>/postcss-media-minmax_v^4.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-media-minmax'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-media-minmax' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'postcss-media-minmax/index' {
  declare module.exports: $Exports<'postcss-media-minmax'>;
}
declare module 'postcss-media-minmax/index.js' {
  declare module.exports: $Exports<'postcss-media-minmax'>;
}
