// flow-typed signature: 8a4b091fc2bfedb64b24872714442873
// flow-typed version: <<STUB>>/postcss-import_v^12.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-import'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-import' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-import/lib/join-media' {
  declare module.exports: any;
}

declare module 'postcss-import/lib/load-content' {
  declare module.exports: any;
}

declare module 'postcss-import/lib/parse-statements' {
  declare module.exports: any;
}

declare module 'postcss-import/lib/process-content' {
  declare module.exports: any;
}

declare module 'postcss-import/lib/resolve-id' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-import/index' {
  declare module.exports: $Exports<'postcss-import'>;
}
declare module 'postcss-import/index.js' {
  declare module.exports: $Exports<'postcss-import'>;
}
declare module 'postcss-import/lib/join-media.js' {
  declare module.exports: $Exports<'postcss-import/lib/join-media'>;
}
declare module 'postcss-import/lib/load-content.js' {
  declare module.exports: $Exports<'postcss-import/lib/load-content'>;
}
declare module 'postcss-import/lib/parse-statements.js' {
  declare module.exports: $Exports<'postcss-import/lib/parse-statements'>;
}
declare module 'postcss-import/lib/process-content.js' {
  declare module.exports: $Exports<'postcss-import/lib/process-content'>;
}
declare module 'postcss-import/lib/resolve-id.js' {
  declare module.exports: $Exports<'postcss-import/lib/resolve-id'>;
}
