// flow-typed signature: 332d135da79c609bc78b127dddc1a75d
// flow-typed version: <<STUB>>/postcss-custom-media_v^7.0.3/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-media'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-media' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-custom-media/index.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-custom-media/index.cjs.js' {
  declare module.exports: $Exports<'postcss-custom-media/index.cjs'>;
}
