// flow-typed signature: 31fd0a084b76e1453c2876aed3c8771f
// flow-typed version: <<STUB>>/postcss-nested_v^4.1.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-nested'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-nested' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */

// Filename aliases
declare module 'postcss-nested/index' {
  declare module.exports: $Exports<'postcss-nested'>;
}
declare module 'postcss-nested/index.js' {
  declare module.exports: $Exports<'postcss-nested'>;
}
