// flow-typed signature: 0d9794248c0f888c2f85a02358fe3fd0
// flow-typed version: <<STUB>>/postcss-loader_v^3.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-loader/src/Error' {
  declare module.exports: any;
}

declare module 'postcss-loader/src/index' {
  declare module.exports: any;
}

declare module 'postcss-loader/src/options' {
  declare module.exports: any;
}

declare module 'postcss-loader/src/Warning' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-loader/src/Error.js' {
  declare module.exports: $Exports<'postcss-loader/src/Error'>;
}
declare module 'postcss-loader/src/index.js' {
  declare module.exports: $Exports<'postcss-loader/src/index'>;
}
declare module 'postcss-loader/src/options.js' {
  declare module.exports: $Exports<'postcss-loader/src/options'>;
}
declare module 'postcss-loader/src/Warning.js' {
  declare module.exports: $Exports<'postcss-loader/src/Warning'>;
}
