// flow-typed signature: 7c6c428f7ac96ca8d262d235fb6b89f6
// flow-typed version: <<STUB>>/postcss-custom-properties_v^8.0.5/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-custom-properties'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-custom-properties' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-custom-properties/index.cjs' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-custom-properties/index.cjs.js' {
  declare module.exports: $Exports<'postcss-custom-properties/index.cjs'>;
}
