// flow-typed signature: 448f7c7181bb876880212af04eda5838
// flow-typed version: <<STUB>>/react-dev-utils_v^5.0.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dev-utils'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dev-utils' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dev-utils/checkRequiredFiles' {
  declare module.exports: any;
}

declare module 'react-dev-utils/clearConsole' {
  declare module.exports: any;
}

declare module 'react-dev-utils/crossSpawn' {
  declare module.exports: any;
}

declare module 'react-dev-utils/errorOverlayMiddleware' {
  declare module.exports: any;
}

declare module 'react-dev-utils/eslintFormatter' {
  declare module.exports: any;
}

declare module 'react-dev-utils/FileSizeReporter' {
  declare module.exports: any;
}

declare module 'react-dev-utils/formatWebpackMessages' {
  declare module.exports: any;
}

declare module 'react-dev-utils/getProcessForPort' {
  declare module.exports: any;
}

declare module 'react-dev-utils/ignoredFiles' {
  declare module.exports: any;
}

declare module 'react-dev-utils/inquirer' {
  declare module.exports: any;
}

declare module 'react-dev-utils/InterpolateHtmlPlugin' {
  declare module.exports: any;
}

declare module 'react-dev-utils/launchEditor' {
  declare module.exports: any;
}

declare module 'react-dev-utils/launchEditorEndpoint' {
  declare module.exports: any;
}

declare module 'react-dev-utils/ModuleScopePlugin' {
  declare module.exports: any;
}

declare module 'react-dev-utils/noopServiceWorkerMiddleware' {
  declare module.exports: any;
}

declare module 'react-dev-utils/openBrowser' {
  declare module.exports: any;
}

declare module 'react-dev-utils/printBuildError' {
  declare module.exports: any;
}

declare module 'react-dev-utils/printHostingInstructions' {
  declare module.exports: any;
}

declare module 'react-dev-utils/WatchMissingNodeModulesPlugin' {
  declare module.exports: any;
}

declare module 'react-dev-utils/WebpackDevServerUtils' {
  declare module.exports: any;
}

declare module 'react-dev-utils/webpackHotDevClient' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dev-utils/checkRequiredFiles.js' {
  declare module.exports: $Exports<'react-dev-utils/checkRequiredFiles'>;
}
declare module 'react-dev-utils/clearConsole.js' {
  declare module.exports: $Exports<'react-dev-utils/clearConsole'>;
}
declare module 'react-dev-utils/crossSpawn.js' {
  declare module.exports: $Exports<'react-dev-utils/crossSpawn'>;
}
declare module 'react-dev-utils/errorOverlayMiddleware.js' {
  declare module.exports: $Exports<'react-dev-utils/errorOverlayMiddleware'>;
}
declare module 'react-dev-utils/eslintFormatter.js' {
  declare module.exports: $Exports<'react-dev-utils/eslintFormatter'>;
}
declare module 'react-dev-utils/FileSizeReporter.js' {
  declare module.exports: $Exports<'react-dev-utils/FileSizeReporter'>;
}
declare module 'react-dev-utils/formatWebpackMessages.js' {
  declare module.exports: $Exports<'react-dev-utils/formatWebpackMessages'>;
}
declare module 'react-dev-utils/getProcessForPort.js' {
  declare module.exports: $Exports<'react-dev-utils/getProcessForPort'>;
}
declare module 'react-dev-utils/ignoredFiles.js' {
  declare module.exports: $Exports<'react-dev-utils/ignoredFiles'>;
}
declare module 'react-dev-utils/inquirer.js' {
  declare module.exports: $Exports<'react-dev-utils/inquirer'>;
}
declare module 'react-dev-utils/InterpolateHtmlPlugin.js' {
  declare module.exports: $Exports<'react-dev-utils/InterpolateHtmlPlugin'>;
}
declare module 'react-dev-utils/launchEditor.js' {
  declare module.exports: $Exports<'react-dev-utils/launchEditor'>;
}
declare module 'react-dev-utils/launchEditorEndpoint.js' {
  declare module.exports: $Exports<'react-dev-utils/launchEditorEndpoint'>;
}
declare module 'react-dev-utils/ModuleScopePlugin.js' {
  declare module.exports: $Exports<'react-dev-utils/ModuleScopePlugin'>;
}
declare module 'react-dev-utils/noopServiceWorkerMiddleware.js' {
  declare module.exports: $Exports<
    'react-dev-utils/noopServiceWorkerMiddleware',
  >;
}
declare module 'react-dev-utils/openBrowser.js' {
  declare module.exports: $Exports<'react-dev-utils/openBrowser'>;
}
declare module 'react-dev-utils/printBuildError.js' {
  declare module.exports: $Exports<'react-dev-utils/printBuildError'>;
}
declare module 'react-dev-utils/printHostingInstructions.js' {
  declare module.exports: $Exports<'react-dev-utils/printHostingInstructions'>;
}
declare module 'react-dev-utils/WatchMissingNodeModulesPlugin.js' {
  declare module.exports: $Exports<
    'react-dev-utils/WatchMissingNodeModulesPlugin',
  >;
}
declare module 'react-dev-utils/WebpackDevServerUtils.js' {
  declare module.exports: $Exports<'react-dev-utils/WebpackDevServerUtils'>;
}
declare module 'react-dev-utils/webpackHotDevClient.js' {
  declare module.exports: $Exports<'react-dev-utils/webpackHotDevClient'>;
}
