// flow-typed signature: 5c035024d992b7f44eaa019b6652cc27
// flow-typed version: <<STUB>>/react-deep-force-update_v^2.1.3/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-deep-force-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-deep-force-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-deep-force-update/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-deep-force-update/lib/index.js' {
  declare module.exports: $Exports<'react-deep-force-update/lib/index'>;
}
