// flow-typed signature: 7604de2dceb57328ca0ab616df029876
// flow-typed version: <<STUB>>/source-map-support_v^0.5.9/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'source-map-support'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'source-map-support' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'source-map-support/browser-source-map-support' {
  declare module.exports: any;
}

declare module 'source-map-support/register' {
  declare module.exports: any;
}

declare module 'source-map-support/source-map-support' {
  declare module.exports: any;
}

// Filename aliases
declare module 'source-map-support/browser-source-map-support.js' {
  declare module.exports: $Exports<
    'source-map-support/browser-source-map-support',
  >;
}
declare module 'source-map-support/register.js' {
  declare module.exports: $Exports<'source-map-support/register'>;
}
declare module 'source-map-support/source-map-support.js' {
  declare module.exports: $Exports<'source-map-support/source-map-support'>;
}
