// flow-typed signature: db3c61b9901d66062685bb9aa1ecbe03
// flow-typed version: <<STUB>>/sqlite3_v^4.0.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sqlite3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sqlite3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sqlite3/lib/index' {
  declare module.exports: any;
}

declare module 'sqlite3/lib/sqlite3' {
  declare module.exports: any;
}

declare module 'sqlite3/lib/trace' {
  declare module.exports: any;
}

declare module 'sqlite3/sqlite3' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sqlite3/lib/index.js' {
  declare module.exports: $Exports<'sqlite3/lib/index'>;
}
declare module 'sqlite3/lib/sqlite3.js' {
  declare module.exports: $Exports<'sqlite3/lib/sqlite3'>;
}
declare module 'sqlite3/lib/trace.js' {
  declare module.exports: $Exports<'sqlite3/lib/trace'>;
}
declare module 'sqlite3/sqlite3.js' {
  declare module.exports: $Exports<'sqlite3/sqlite3'>;
}
