// flow-typed signature: 5bf1d5da362f0115fd1c19e6efc4514f
// flow-typed version: <<STUB>>/universal-router_v^6.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'universal-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'universal-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'universal-router/generateUrls/index' {
  declare module.exports: any;
}

declare module 'universal-router/generateUrls/module' {
  declare module.exports: any;
}

declare module 'universal-router/module' {
  declare module.exports: any;
}

declare module 'universal-router/src/generateUrls' {
  declare module.exports: any;
}

declare module 'universal-router/src/matchPath' {
  declare module.exports: any;
}

declare module 'universal-router/src/matchRoute' {
  declare module.exports: any;
}

declare module 'universal-router/src/resolveRoute' {
  declare module.exports: any;
}

declare module 'universal-router/src/UniversalRouter' {
  declare module.exports: any;
}

declare module 'universal-router/universal-router-generate-urls' {
  declare module.exports: any;
}

declare module 'universal-router/universal-router-generate-urls.min' {
  declare module.exports: any;
}

declare module 'universal-router/universal-router' {
  declare module.exports: any;
}

declare module 'universal-router/universal-router.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'universal-router/generateUrls/index.js' {
  declare module.exports: $Exports<'universal-router/generateUrls/index'>;
}
declare module 'universal-router/generateUrls/module.js' {
  declare module.exports: $Exports<'universal-router/generateUrls/module'>;
}
declare module 'universal-router/index' {
  declare module.exports: $Exports<'universal-router'>;
}
declare module 'universal-router/index.js' {
  declare module.exports: $Exports<'universal-router'>;
}
declare module 'universal-router/module.js' {
  declare module.exports: $Exports<'universal-router/module'>;
}
declare module 'universal-router/src/generateUrls.js' {
  declare module.exports: $Exports<'universal-router/src/generateUrls'>;
}
declare module 'universal-router/src/matchPath.js' {
  declare module.exports: $Exports<'universal-router/src/matchPath'>;
}
declare module 'universal-router/src/matchRoute.js' {
  declare module.exports: $Exports<'universal-router/src/matchRoute'>;
}
declare module 'universal-router/src/resolveRoute.js' {
  declare module.exports: $Exports<'universal-router/src/resolveRoute'>;
}
declare module 'universal-router/src/UniversalRouter.js' {
  declare module.exports: $Exports<'universal-router/src/UniversalRouter'>;
}
declare module 'universal-router/universal-router-generate-urls.js' {
  declare module.exports: $Exports<
    'universal-router/universal-router-generate-urls',
  >;
}
declare module 'universal-router/universal-router-generate-urls.min.js' {
  declare module.exports: $Exports<
    'universal-router/universal-router-generate-urls.min',
  >;
}
declare module 'universal-router/universal-router.js' {
  declare module.exports: $Exports<'universal-router/universal-router'>;
}
declare module 'universal-router/universal-router.min.js' {
  declare module.exports: $Exports<'universal-router/universal-router.min'>;
}
