// flow-typed signature: bfc0908040702efbe7d142c849f43b61
// flow-typed version: <<STUB>>/webpack-dev-middleware_v^3.3.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-dev-middleware'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-dev-middleware' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-dev-middleware/lib/context' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/lib/DevMiddlewareError' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/lib/fs' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/lib/middleware' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/lib/reporter' {
  declare module.exports: any;
}

declare module 'webpack-dev-middleware/lib/util' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-dev-middleware/index' {
  declare module.exports: $Exports<'webpack-dev-middleware'>;
}
declare module 'webpack-dev-middleware/index.js' {
  declare module.exports: $Exports<'webpack-dev-middleware'>;
}
declare module 'webpack-dev-middleware/lib/context.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/lib/context'>;
}
declare module 'webpack-dev-middleware/lib/DevMiddlewareError.js' {
  declare module.exports: $Exports<
    'webpack-dev-middleware/lib/DevMiddlewareError',
  >;
}
declare module 'webpack-dev-middleware/lib/fs.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/lib/fs'>;
}
declare module 'webpack-dev-middleware/lib/middleware.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/lib/middleware'>;
}
declare module 'webpack-dev-middleware/lib/reporter.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/lib/reporter'>;
}
declare module 'webpack-dev-middleware/lib/util.js' {
  declare module.exports: $Exports<'webpack-dev-middleware/lib/util'>;
}
