// flow-typed signature: 280078e0ef7482efc89cd964ad4cbe45
// flow-typed version: <<STUB>>/webpack-assets-manifest_v^3.0.2/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-assets-manifest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-assets-manifest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-assets-manifest/src/helpers' {
  declare module.exports: any;
}

declare module 'webpack-assets-manifest/src/WebpackAssetsManifest' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-assets-manifest/src/helpers.js' {
  declare module.exports: $Exports<'webpack-assets-manifest/src/helpers'>;
}
declare module 'webpack-assets-manifest/src/WebpackAssetsManifest.js' {
  declare module.exports: $Exports<
    'webpack-assets-manifest/src/WebpackAssetsManifest',
  >;
}
