import { basename, join } from "node:path";
import { Glob } from "bun";

const packageDir = join(import.meta.dirname, "..");
const indexFile = join(packageDir, "index.ts");

/** Package source files subject to mechanical postprocessing. */
const sourceGlobs = [
  "components/**/*.{ts,tsx}",
  "hooks/**/*.{ts,tsx}",
  "lib/**/*.{ts,tsx}",
];

/**
 * Run a command from the package root, throwing on a non-zero exit.
 *
 * `cwd` is pinned rather than inherited: the shadcn CLI reads `components.json`
 * from its working directory, so a script invoked from anywhere else would
 * otherwise configure itself from the wrong workspace.
 */
export async function execCommand(
  command: string,
  args: string[],
): Promise<void> {
  const proc = Bun.spawn([command, ...args], {
    cwd: packageDir,
    stdio: ["inherit", "inherit", "inherit"],
  });

  const exitCode = await proc.exited;
  if (exitCode !== 0) {
    throw new Error(`Command failed: ${command} ${args.join(" ")}`);
  }
}

/** Top-level primitives – the package's public API. */
export async function installedComponents(): Promise<string[]> {
  const glob = new Glob("*.tsx");
  const names: string[] = [];

  for await (const file of glob.scan(join(packageDir, "components"))) {
    names.push(basename(file, ".tsx"));
  }

  return names.sort();
}

async function sourceFiles(): Promise<string[]> {
  const files: string[] = [];

  for (const pattern of sourceGlobs) {
    const glob = new Glob(pattern);
    for await (const file of glob.scan({ cwd: packageDir, absolute: true })) {
      files.push(file);
    }
  }

  return files.sort();
}

/**
 * Some registry items still carry `"use client"` even though `components.json`
 * sets `rsc: false`. Nothing here is a React Server Component, so the directive
 * is dead weight that would otherwise reappear in every update diff.
 */
async function stripUseClient(files: string[]): Promise<void> {
  for (const file of files) {
    const source = await Bun.file(file).text();
    const stripped = source.replace(/^\s*["']use client["'];?\s*\n/, "");

    if (stripped !== source) {
      await Bun.write(file, stripped);
    }
  }
}

/** Rebuild the barrel – the CLI writes component files but never exports them. */
async function syncBarrelExports(): Promise<void> {
  const names = await installedComponents();

  await Bun.write(
    indexFile,
    [
      "/**",
      " * @file UI component library entrypoint.",
      " *",
      " * Generated by `bun ui:add` / `bun ui:update`. Exports the top-level",
      " * primitives in `components/`; anything nested is an implementation detail.",
      " */",
      "",
      ...names.map((name) => `export * from "./components/${name}";`),
      "",
      'export * from "./lib/utils";',
      "",
    ].join("\n"),
  );
}

/**
 * Normalize the package source tree after a registry operation, regenerate the
 * barrel, and format.
 *
 * Sweeps every source file rather than tracking what the CLI just wrote:
 * registry items pull in their dependencies, so the changed set can be wider
 * than the names requested, and a full sweep needs no before/after bookkeeping.
 */
export async function postprocessComponents(): Promise<void> {
  const files = await sourceFiles();

  if (files.length === 0) {
    throw new Error(`No source files found under ${packageDir}`);
  }

  await stripUseClient(files);
  await syncBarrelExports();
  await execCommand("bunx", ["prettier", "--write", ...files, indexFile]);
}
