// flow-typed signature: 59952b4218b8e8a7a6fc51e48013ce9f
// flow-typed version: <<STUB>>/@babel/plugin-transform-react-constant-elements_v^7.0.0/flow_v0.92.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@babel/plugin-transform-react-constant-elements'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@babel/plugin-transform-react-constant-elements' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@babel/plugin-transform-react-constant-elements/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module '@babel/plugin-transform-react-constant-elements/lib/index.js' {
  declare module.exports: $Exports<
    '@babel/plugin-transform-react-constant-elements/lib/index',
  >;
}
