/* eslint-disable import/prefer-default-export */

export const SET_RUNTIME_VARIABLE = 'SET_RUNTIME_VARIABLE';
export const SET_LOCALE_START = 'SET_LOCALE_START';
export const SET_LOCALE_SUCCESS = 'SET_LOCALE_SUCCESS';
export const SET_LOCALE_ERROR = 'SET_LOCALE_ERROR';
export const GET_LOCALE_CONTENT = 'GET_LOCALE_CONTENT';
export const GET_LOCALE_CONTENT_SUCCESS = 'GET_LOCALE_CONTENT_SUCCESS';
export const GET_LOCALE_CONTENT_ERROR = 'GET_LOCALE_CONTENT_ERROR';
