/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false core/types/cloudflare-env.d.ts` (hash: 80ac32e7a486bfa7e2f6fce3cedf3e18)
declare namespace Cloudflare {
  interface Env {
    ENVIRONMENT: "development" | "production" | "preview";
    DATABASE_URL: "postgres://root@localhost:5432/example";
    ALLOWED_ORIGINS:
      | "http://localhost:5173,http://127.0.0.1:5173"
      | "https://example.com"
      | "https://preview.example.com";
    DB: D1Database;
    HYPERDRIVE: Hyperdrive;
    ASSETS: Fetcher;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<Cloudflare.Env, "ENVIRONMENT" | "DATABASE_URL" | "ALLOWED_ORIGINS">
    > {}
}
