/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule Header_me.graphql
 * @generated SignedSource<<c0aea0fde0c6318c51809ffb6df6f792>>
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteFragment} from 'relay-runtime';
export type Header_me = { };
*/

/* eslint-disable comma-dangle, quotes */

const fragment /*: ConcreteFragment*/ = {
  "argumentDefinitions": [],
  "kind": "Fragment",
  "metadata": null,
  "name": "Header_me",
  "selections": [
    {
      "kind": "FragmentSpread",
      "name": "Navigation_me",
      "args": null
    }
  ],
  "type": "User"
};

module.exports = fragment;
