/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false ./edge/lib/types.d.ts` (hash: 5aff64c6380a800007b09f3b8a2d171b)
declare namespace Cloudflare {
  interface Env {
    ENV: "production";
    db: D1Database;
    ASSETS: Fetcher;
    BETTER_AUTH_SECRET: string;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ENV">> {}
}
