/**
 * This file was generated by:
 *   relay-compiler
 *
 * @providesModule indexNotFoundQuery.graphql
 * @generated SignedSource<<bc05898efe63f9a583cbac704fd1bcab>>
 * @relayHash d8c1907a12cc4939ea967cc1217bba2d
 * @flow
 * @nogrep
 */

'use strict';

/*::
import type {ConcreteBatch} from 'relay-runtime';

*/

/* eslint-disable comma-dangle, quotes */

/*
query indexNotFoundQuery {
  me {
    ...Layout_me
    id
  }
}

fragment Layout_me on User {
  ...Header_me
}

fragment Header_me on User {
  ...Navigation_me
}

fragment Navigation_me on User {
  email
}
*/

const batch /*: ConcreteBatch*/ = {
  "fragment": {
    "argumentDefinitions": [],
    "kind": "Fragment",
    "metadata": null,
    "name": "indexNotFoundQuery",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "me",
        "plural": false,
        "selections": [
          {
            "kind": "FragmentSpread",
            "name": "Layout_me",
            "args": null
          }
        ],
        "storageKey": null
      }
    ],
    "type": "Query"
  },
  "id": null,
  "kind": "Batch",
  "metadata": {},
  "name": "indexNotFoundQuery",
  "query": {
    "argumentDefinitions": [],
    "kind": "Root",
    "name": "indexNotFoundQuery",
    "operation": "query",
    "selections": [
      {
        "kind": "LinkedField",
        "alias": null,
        "args": null,
        "concreteType": "User",
        "name": "me",
        "plural": false,
        "selections": [
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "email",
            "storageKey": null
          },
          {
            "kind": "ScalarField",
            "alias": null,
            "args": null,
            "name": "id",
            "storageKey": null
          }
        ],
        "storageKey": null
      }
    ]
  },
  "text": "query indexNotFoundQuery {\n  me {\n    ...Layout_me\n    id\n  }\n}\n\nfragment Layout_me on User {\n  ...Header_me\n}\n\nfragment Header_me on User {\n  ...Navigation_me\n}\n\nfragment Navigation_me on User {\n  email\n}\n"
};

module.exports = batch;
