# GitHub Actions workflow
# https://help.github.com/actions
# https://www.conventionalcommits.org

name: "Conventional Commits"

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  lint:
    name: "Lint PR Title"
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
